# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']

# Site Settings
title: "Material Fest. Un evento enfocado a diseñadores digitales y desarrolladores móviles. "
email: "materialfest@gmail.com"
description: "Aquí no veras teoría, sólo practica hablando desde la experiencia. ¿En donde? En Cádiz."
#baseurl: "/zeppelin"
baseurl: ""
url: "http://materialfest.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "jorgegalindocruces.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Cádiz & The Singulars"
organizerAlternateName: "Google Developer Group Cádiz & The Singulars"
organizerDescription: "GDG Cádiz & The Sigulars se unen para ofrecer un evento orientado tanto a diseño como en desarrollo con un foco común. Material"
organizerEmail: "materialfest@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://plus.google.com/u/1/112866714526515716260/about"

# Head
metaKeywords: "event, material, android-l, devfest, google, desarrollo, diseño, android, chrome, developers, Cádiz"
twitterAccount: "@MaterialFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://jorgegalindocruces.typeform.com/to/ADJFdK"
c4sponsorsUrl: "mailto:materialfest@gmail.com"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Ponentes"}
 - {permalink: "/team/", text: "Equipo"}
 - {permalink: "/logistics/", text: "Logística"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "http://materialfest.eventbrite.es", text: "Entradas"}
rightNavigationButtons:
 - {link: "http://8materialfest.eventbrite.es", text: "Entradas"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Un evento sobre <typeout>"
eventDate: "¿Cuando? El 31 De Enero. ¿Donde? En Cádiz"
typeoutTextValues: '"Diseño Digital", "Desarrollo Móvil", "Experiencia"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://jorgegalindocruces.typeform.com/to/ADJFdK", text: "Call For Papers"}
 - {permalink: "/#tickets", text: "¡Quiero ir!"}

# About Block
aboutTitle: "Acerca de Material Def Fest"
aboutBlock:
 - {title: "Un track enfocado en diseño digital", image: "about-section-track-Design.jpg", text: "Charlas sobre tipografía, Material Design, iconografía y guías de estilo. Todo enfocado a móvil" }
 - {title: "Un track enfocado a desarrollo Android", image: "about-section-track_Develop.jpg", text: "Charlas sobre 'frontend en Android', animaciones y programación funcional" }
 - {title: "Eventos paralelos sobre UX y mesas redondas", image: "about-section-track-Workshop.jpg", text: "Un campeonato de mini ping-pong, mesas redondas y workshops sobre UX" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "asistentes", detail: "de todos sitios"}
 - {count: "12", specialCharacter: "+", info: "horas", detail: "de diversión y conocimiento"}
 - {count: "16", specialCharacter: "+", info: "speakers", detail: "de compañias internacionales"}
 - {count: "3", specialCharacter: "", info: "Tracks", detail: "Diseño, Desarrollo y mesas redondas"}

# Latest News Block
latestNewsTitle: "Ultimas noticias"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "Echa un ojo a nuestro cartel"

# Location Block
locationBlockTitle: "Localización"
eventLocationName: "Aulario La Bomba. Cádiz"
eventLocationLink: "https://plus.google.com/114799348666220805362/about?gl=es&hl=es"
eventStreetAddress: "Justo al lado de la Caleta"
eventAddressLocality: "Cádiz"
eventAddressLocalityRegion: "Andalucía"
eventPostalCode: "11001"
eventAddressCountry: "Spain"
eventStartTime: "2014-01-31T10:00"
eventDoorTime: "09:00"
eventEndTime: "2015-01-31T20:00"
eventPlaceCoordinates: "36.537189, -6.301627"
mapCenterCoordinates: "36.537189, -6.301627"
mapMobileCenterCoordinates: "36.537189, -6.301627"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Aulario La Bomba"
venueFeatures: ["En el casco antiguo de Cádiz", "Dos salas para los tracks independientes", "Un patio para las actividades y mesas redondas"]

# Tweets Feed Block
tweetsFeedImage: "rockstar-speakers.jpg"
tweetsFeedTitle: "¿Que esta pasando?"
twitterHashTag: "materialFest"
twitterFeed: "http://enterwebdesign.es/blog_jgc/tweetledee/searchjson.php?q=Material"

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Partners"
partnersC4sponsorsButton: "¿Te molaría ser nuestro sponsor? ¿Quieres molar de verdad?"

# Subscribe Block
subscribeImage: "rockstar-speakers.jpg"
subscribeTitle: "Subscribete a nuestra Newsletter"
subscribeAction: "http://47deg.us6.list-manage.com/subscribe?u=66b615bef6&id=70c8bcf5e6"
subscribeInfo: "El registro se abrirá en Enero. El numero de entradas es limitado... Stay tuned!"

# Tickets Block
ticketsTitle: "¿Cuanto cuesta?"
ticketsInfo: "La entrada al evento asegurará la participación de cualquier evento o mesa redonda y la posibilidad de asistir a todas las charlas. Todo superavit se invertirá en confort"
ticketsOffers:
 -
  name: "Early Bird"
  price: "12"
  priceCurrency: "Euros"
  ticketsNumber: "12"
  ribbon: "-20%"
  buyButtonLink: "https://materialfest.eventbrite.es"
  buyButtonText: "¡Compralo ahora!"
  ticketContentList: ["Si eres el más rápido del oeste te saldrá barato", "Sabés que lo vale y después te arrepentiras", "Acceso a todas las charlas y participación en actividades"]
  validFrom: "2014-12-16T10:00"
  validThrough: "2015-01-15T23:59"
 -
  name: "Ultima oportunidad"
  price: "15"
  priceCurrency: "Euros"
  ticketsNumber: "100"
  featured: true
  buyButtonLink: "https://materialfest.eventbrite.es"
  buyButtonText: "¡Compralo ahora!"
  ticketContentList: ["Sólo en la última semana del evento", "Accede a uno de los mejores eventos para desarrolladores y diseñadores de Andalucía", "Acceso a todas las charlas y participación en actividades"]
  validFrom: "2015-01-15T23:59"
  validThrough: "2015-01-30T23:59"
  disabled: true
 -
  name: "Estudiante"
  price: "10"
  priceCurrency: "Euros"
  ribbon: "-33%"
  ticketsNumber: "100"
  buyButtonLink: "https://materialfest.eventbrite.es"
  buyButtonText: "¡Compralo ahora!"
  additionalInfo: "Requiere en el intercambio de la entrada, mostrar el carnet universitario o la identificación de estudiantes"
  ticketContentList: ["¿Eres un futuro de diseñador o desarrollador?", "Valido para Universitarios y estudiantes de FP", "¡Ya no tienes excusa!"]
  validFrom: "2014-12-16T10:00"
  validThrough: "2014-10-23T23:59"
#  soldOut: true
#  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://plus.google.com/u/1/112866714526515716260/posts", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=materialfest", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://plus.google.com/u/1/112866714526515716260/posts", text: "GDG Cádiz"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contactar"
  links:
   - {link: "mailto:materialfest@gmail.com", text: "materialfest@gmail.com"}
 -
  title: "FAQ"
  links:
#   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Últimas noticias"
blogCommentsEnabled: true
discusShortName: "materialfest"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Acerca de nosotros"
aboutUs: "Somos una cocktail mezclado pero no agitado de desarrolladores, diseñadores y periodistas que llevan meses trabajando en traer a Cádiz un evento con una calidad cercana al Atún de Almadraba"

# Logistics Find Way Block
findWayTitle: "Te lo ponemos facil! Te decimos hasta como venir!"
findWayDistance: "Distancia"
findWayDriving: "En coche"
findWayWalking: "Andando"
findWayBicycling: "En bicicleta"
findWayTransit: "En tren"
findWayFindFlight: "Encuentra un vuelo"
logisticsMapCenterCoordinates: "36.537189, -6.301627"
logisticsMapMobileCenterCoordinates: "36.537189, -6.301627"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "¿Que hay en Cádiz?"
directionDetailsCards:
 - {title: "Desde el Aeropuerto", information: 'Cádiz tiene aeropuerto cerca... En Jerez! Esta cerquita de Cádiz y puedes venir de multitud de formas... <a href="http://www.aena-aeropuertos.es/csee/Satellite/Aeropuerto-Jerez/en/">Link Aeropuerto</a>.'}
 - {title: "Transporte público", information: 'Si os digo la verdad... la forma preferible de venir a Cádiz es en tren. Os deja en el centro y esta lleno de confort'}
 - {title: "Hoteles", information: 'Cádiz es lugar de vacaciones y hay tela de sitios guapetones donde elegir... Aquí os dejamos unos cuantos!'}
directionDetailsWideCards: 
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}


# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "36.537189, -6.301627"
hackathonMapCenterCoordinates: "36.537189, -6.301627"
hackathonMapMobileCenterCoordinates: "36.537189, -6.301627"